docs/AUTH.md
src/main/java/com/example/picket/common/annotation/Auth.java
src/main/java/com/example/picket/common/auth/AuthUserArgumentResolver.java
src/main/java/com/example/picket/common/consts/Const.java
src/main/java/com/example/picket/common/dto/AuthUser.java
src/main/java/com/example/picket/common/exception/ErrorCode.java
src/main/java/com/example/picket/common/exception/GlobalExceptionHandler.java
src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
src/main/java/com/example/picket/config/WebConfig.java
src/main/java/com/example/picket/domain/auth/controller/AuthController.java
src/main/java/com/example/picket/domain/auth/dto/request/SigninRequest.java
src/main/java/com/example/picket/domain/auth/dto/request/SignupRequest.java
src/main/java/com/example/picket/domain/auth/dto/response/SigninResponse.java
src/main/java/com/example/picket/domain/auth/service/AuthService.java
src/main/java/com/example/picket/domain/user/repository/UserRepository.java

- 회원가입(유저) API 구현
- 회원가입(디렉터) API 구현
- 회원가입(관리자) API 구현
- 로그인 API 구현
- 로그아웃 API 구현
-> Postman을 통해 정상적으로 동작하는지 확인 완료
closes #1 , #12 , #14 , #18 , #19

인증/인가 API 구현

---

src/main/java/com/example/picket/common/auth/AuthUserArgumentResolver.java
src/main/java/com/example/picket/common/enums/Category.java
src/main/java/com/example/picket/common/enums/Gender.java
src/main/java/com/example/picket/common/enums/Grade.java
src/main/java/com/example/picket/common/enums/TicketStatus.java
src/main/java/com/example/picket/common/enums/UserRole.java
src/main/java/com/example/picket/common/exception/ErrorCode.java
src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
src/main/java/com/example/picket/domain/auth/service/AuthService.java

- ErrorCode Convention에 맞게 수정
-> Postman을 통해 정상적으로 동작하는지 확인 완료
closes #24

인증/인가 ErrorCode 수정

---

src/main/java/com/example/picket/common/dto/AuthUser.java
src/main/java/com/example/picket/domain/auth/controller/AuthController.java
src/main/java/com/example/picket/domain/auth/dto/response/SigninResponse.java
src/main/java/com/example/picket/domain/auth/service/AuthService.java
src/main/java/com/example/picket/domain/user/entity/User.java

- Service 메서드에서 Entity 반환할 수 있도록 수정.
- Static Factory Method 적용
-> Postman을 통해 정상적으로 동작하는지 확인 완료
closes #24

인증/인가 DTO 및 Entity 관련 수정

---

src/main/java/com/example/picket/common/exception/ErrorCode.java
src/main/java/com/example/picket/domain/ticket/controller/TicketController.java
src/main/java/com/example/picket/domain/ticket/service/TicketQueryService.java

📌 반영 브랜치
feat/ticket -> dev
✅ 작업 내용
티켓 단건 조회 시 본인이 예매한 티켓만 조회할 수 있도록 수정
🎯 단독 테스트 결과
-> Postman을 통해 정상적으로 동작하는지 확인 완료
🚨 연관 이슈
closes #25

Ticket : 티켓 단건 조회 API 수정

---

.gitignore
src/main/java/com/example/picket/domain/comment/service/CommentCommandService.java
src/main/java/com/example/picket/domain/like/service/LikeCommandService.java
src/main/java/com/example/picket/domain/like/service/LikeQueryService.java
src/main/java/com/example/picket/domain/seat/repository/SeatRepository.java
src/main/java/com/example/picket/domain/seat/service/SeatCommandService.java
src/main/java/com/example/picket/domain/seat/service/SeatQueryService.java
src/main/java/com/example/picket/domain/show/service/ShowCommandService.java
src/main/java/com/example/picket/domain/show/service/ShowDateCommandService.java
src/main/java/com/example/picket/domain/show/service/ShowDateQueryService.java
src/main/java/com/example/picket/domain/show/service/ShowQueryService.java
src/main/java/com/example/picket/domain/show/service/ShowResponseMapper.java
src/main/java/com/example/picket/domain/ticket/service/TicketCommandService.java
src/main/java/com/example/picket/domain/user/controller/UserController.java
src/main/java/com/example/picket/domain/user/service/UserCommandService.java
src/main/java/com/example/picket/domain/user/service/UserQueryService.java
src/main/resources/application.yml

refactor/di -> dev
- User, Auth, Like, Seat, Show, ShowDate, Ticket의 DI 부분을 Service가 받을 수 있도록 리팩토링
-> Postman을 통해 회원가입 및 로그인, 좋아요 관련 기능까지는 정상적으로 동작하는 것을 확인
-> 나머지 부분은 이후 완성 시 다시 테스트 돌려 봐야 할 것 같습니다.
closes #42

Repository -> Service로 DI 리팩토링

---

src/test/java/com/example/picket/domain/auth/service/AuthServiceTest.java

- 회원가입, 로그인, 로그아웃에 대한 Service 단위 테스트 코드 작성
- 예외 상황에 대한 검증 로직 포함
- 서비스 DI 변경(repository -> service) 반영 완료 
- 로컬 테스트 기준 단위 테스트 통과
closes #41

인증/인가 테스트 코드 작성

---

src/main/java/com/example/picket/domain/comment/service/CommentCommandService.java
src/main/java/com/example/picket/domain/ticket/repository/TicketRepository.java
src/test/java/com/example/picket/domain/comment/service/CommentCommandServiceTest.java
src/test/java/com/example/picket/domain/comment/service/CommentQueryServiceTest.java

feat/comment -> dev
- 댓글 작성, 삭제, 수정에 대한 Service 단위 테스트 코드 작성
- 사용자 권한 및 예외 상황(댓글이 없거나, 삭제 권한 없음 등)에 대한 검증 로직 포함
- 서비스 DI 변경(repository -> service) 반영 완료 
- 로컬 테스트 기준 단위 테스트 통과
closes #45

댓글 테스트 코드 작성

---

src/main/java/com/example/picket/domain/seat/dto/request/SeatUpdateRequest.java
src/main/java/com/example/picket/domain/seat/service/SeatCommandService.java
src/main/java/com/example/picket/domain/show/dto/request/ShowDateRequest.java
src/test/java/com/example/picket/domain/seat/service/SeatCommandServiceTest.java
src/test/java/com/example/picket/domain/seat/service/SeatQueryServiceTest.java
src/test/java/com/example/picket/domain/seat/service/SeatResponseMapperTest.java

feat/show -> dev
좌석 추가, 취소, 조회, 수정에 대한 Service 단위 테스트 코드 작성
예외 상황에 대한 검증 로직 포함
로컬 테스트 기준 단위 테스트 통과
단, SeatCommandServiceTest의 경우 Line Coverage = 97%인데, 이는 SeatCommandService 내의 saveAll 메서드를 ShowCommandService에서 사용하기 때문에 이 경우는 제외함.
#57

좌석 테스트코드 작성

---

src/main/java/com/example/picket/domain/comment/service/CommentCommandService.java
src/main/java/com/example/picket/domain/like/service/LikeCommandService.java
src/main/java/com/example/picket/domain/like/service/LikeQueryService.java
src/main/java/com/example/picket/domain/seat/dto/request/SeatCreateRequest.java
src/main/java/com/example/picket/domain/seat/service/SeatCommandService.java
src/main/java/com/example/picket/domain/show/controller/ShowController.java
src/main/java/com/example/picket/domain/show/dto/request/ShowCreateRequest.java
src/main/java/com/example/picket/domain/show/dto/request/ShowDateRequest.java
src/main/java/com/example/picket/domain/show/dto/request/ShowUpdateRequest.java
src/main/java/com/example/picket/domain/show/entity/Show.java
src/main/java/com/example/picket/domain/show/repository/ShowDateRepository.java
src/main/java/com/example/picket/domain/show/repository/ShowRepository.java
src/main/java/com/example/picket/domain/show/service/ShowCommandService.java
src/main/java/com/example/picket/domain/show/service/ShowDateCommandService.java
src/main/java/com/example/picket/domain/show/service/ShowDateQueryService.java
src/main/java/com/example/picket/domain/show/service/ShowQueryService.java
src/main/java/com/example/picket/domain/ticket/service/TicketCommandService.java
src/test/java/com/example/picket/domain/comment/service/CommentCommandServiceTest.java
src/test/java/com/example/picket/domain/like/service/LikeCommandServiceTest.java
src/test/java/com/example/picket/domain/like/service/LikeQueryServiceTest.java
src/test/java/com/example/picket/domain/seat/service/SeatCommandServiceTest.java
src/test/java/com/example/picket/domain/show/service/ShowCommandServiceTest.java
src/test/java/com/example/picket/domain/show/service/ShowDateCommandServiceTest.java
src/test/java/com/example/picket/domain/show/service/ShowDateQueryServiceTest.java
src/test/java/com/example/picket/domain/show/service/ShowQueryServiceTest.java
src/test/java/com/example/picket/domain/ticket/service/TicketCommandServiceTest.java

test/show -> dev
- Show, ShowDate Service 코드 작성
- ShowUpdateRequest Valid 기능 추가
- READ 컨벤션 find -> get 으로 수정
- 전체 테스트 통과
- 해당 도메인 Service 테스트 커버리지 검증 완료
closes #51

Show, ShowDate 테스트 코드 작성 및 메서드 이름 리팩토링

---

src/main/java/com/example/picket/domain/seat/controller/SeatController.java
src/main/java/com/example/picket/domain/seat/dto/request/SeatCreateRequest.java
src/main/java/com/example/picket/domain/seat/dto/request/SeatUpdateRequest.java

feat/show-> dev
Swagger 사용에 따라 Controller 및 Request Dto에 어노테이션 추가
Swagger 사용에 따라 Controller 및 Request Dto에 어노테이션 추가
#67

좌석 Swagger 설정 적용

---

src/main/java/com/example/picket/domain/user/controller/UserController.java
src/main/java/com/example/picket/domain/user/dto/request/UpdatePasswordRequest.java
src/main/java/com/example/picket/domain/user/dto/request/UpdateUserRequest.java
src/main/java/com/example/picket/domain/user/dto/request/WithdrawUserRequest.java

📌 반영 브랜치
feat/user -> dev
✅ 작업 내용
Swagger(SpringDoc) 기반 API 문서화 환경 구축
User API 문서 처리
📄 주요 작업
Swagger 설정 클래스(SwaggerConfig) 추가
Swagger 문서에서 @Auth 파라미터가 requestBody에 포함되지 않도록 @Parameter(hidden = true) 처리

User Swagger 적용

---

src/main/java/com/example/picket/domain/auth/controller/AuthController.java
src/main/java/com/example/picket/domain/auth/dto/request/SigninRequest.java
src/main/java/com/example/picket/domain/auth/dto/request/SignupRequest.java

📌 반영 브랜치
✅ 작업 내용
Swagger(SpringDoc) 기반 API 문서화 환경 구축
Auth API 문서 처리
close #65

인증/인가 Swagger 적용

---

src/main/java/com/example/picket/domain/like/controller/LikeController.java

📌 반영 브랜치
feat/like -> dev
✅ 작업 내용
Swagger(SpringDoc) 기반 API 문서화 환경 구축
Like API 문서 처리
close #66

좋아요 Swagger 적용

---

src/main/java/com/example/picket/domain/show/entity/ShowDate.java
src/main/java/com/example/picket/domain/ticket/service/TicketCommandService.java
src/test/java/com/example/picket/domain/ticket/service/TicketCommandServiceTest.java

📌 반영 브랜치
reat/ticket -> dev
✅ 작업 내용 리팩토링 중 해당되는 태그
티켓 생성 시 availableSeatCount 감소, reservedSeatCount 증가 하도록 수정
🎯 단독 테스트 결과
테스트 코드 테스트 완료
포스트맨 테스트 완료
🚨 연관 이슈
closes #2

티켓 생성 기능 수정  

---

src/main/java/com/example/picket/domain/seat/repository/jdbc/SeatJdbcRepository.java
src/main/java/com/example/picket/domain/seat/repository/jdbc/SeatJdbcRepositoryImpl.java
src/main/java/com/example/picket/domain/seat/service/SeatCommandService.java
src/main/java/com/example/picket/domain/show/controller/ShowController.java
src/main/java/com/example/picket/domain/show/repository/jdbc/ShowDateJdbcRepository.java
src/main/java/com/example/picket/domain/show/repository/jdbc/ShowDateJdbcRepositoryImpl.java
src/main/java/com/example/picket/domain/show/repository/querydsl/ShowQueryDslRepositoryImpl.java
src/main/java/com/example/picket/domain/show/service/ShowCommandService.java
src/main/java/com/example/picket/domain/show/service/ShowDateCommandService.java
src/main/resources/application.yml
src/test/java/com/example/picket/domain/show/service/ShowCommandServiceTest.java

📌 반영 브랜치
refactor/show/bulk -> dev
✅ 작업 내용 기능 개선 중 해당되는 태그
- 공연 생성 로직 Bulk Insert 로 수정 완료
- 공연 생성 테스트 코드 수정
🎯 단독 테스트 결과
- POSTMAN 성능 테스트 완료
- Test Coverage 검증 완료
🚨 연관 이슈
closes #78

공연 생성 Bulk Insert 적용 및 테스트 코드 수정

---

src/test/java/com/example/picket/domain/auth/service/AuthServiceTest.java

- AuthServiceTest 부분 에러 수정
- 전체 테스트 동작 확인
closes #81

AuthServiceTest 에러 수정

---

build.gradle
src/main/java/com/example/picket/common/enums/SeatStatus.java
src/main/java/com/example/picket/domain/booking/controller/SeatHoldingController.java
src/main/java/com/example/picket/domain/booking/dto/request/SeatHoldingRequest.java
src/main/java/com/example/picket/domain/booking/service/SeatHoldingService.java
src/main/resources/application.yml

📌 반영 브랜치
feat/booking -> dev
✅ 작업 내용 
좌석 선점 API 구현하였습니다.
제가 잘못 찾아보아서 trySet이 deprecated 되었다는 걸 이제 알았습니다. 따라서 setIfAbsent 함수로 구현하였습니다. 
관련 내용 테크스펙 수정하겠습니다! 
🎯 단독 테스트 결과
Swagger 테스트 확인 완료 + redis-cli로 확인하였습니다.
🚨 연관 이슈
closes #86

좌석선점 API 구현

---

build.gradle
docker-compose.yml
docs/MONITORING.md
monitoring/JVM (Micrometer).json
monitoring/Spring Boot 2.1 System Monitor.json
src/main/resources/application-local.yml
src/main/resources/application.yml

feat/monitoring -> dev
- Local 환경에서 Prometheus 및 Grafana 사용
- Prod 환경에서 Prometheus 및 Grafana 사용
- Local 환경 테스트 완료
- Prod 환경 Grafana 및 Prometheus 연결 확인 완료
- Prod 환경 actuator 데이터 수집 결과 확인해봐야함
closes #87

모니터링 도구(Actuator, Prometheus, Grafana) 추가하기

---

src/main/resources/application-prod.yml

feat/oauth -> dev
-> redirectUri 수정

refactor : redirectUri 수정

---

build.gradle
src/main/java/com/example/picket/common/scheduler/ImageRemoveScheduler.java
src/main/java/com/example/picket/common/service/S3Service.java
src/main/java/com/example/picket/domain/images/repository/ShowImageRepository.java
src/main/java/com/example/picket/domain/images/repository/UserImageRepository.java
src/main/java/com/example/picket/domain/show/controller/ShowController.java
src/main/java/com/example/picket/domain/show/service/ShowCommandService.java
src/main/java/com/example/picket/domain/user/controller/UserController.java
src/main/java/com/example/picket/domain/user/service/UserCommandService.java
src/test/java/com/example/picket/common/service/S3ServiceTest.java
src/test/java/com/example/picket/domain/show/service/ShowCommandServiceTest.java
src/test/java/com/example/picket/domain/user/service/UserCommandServiceTest.java

📌 반영 브랜치
feat/image -> dev
✅ 작업 내용
- BaseEntity를 활용하여 최적화 리팩토링을 진행
- 삭제시 deletedAt을 업데이트
- 이후 스케줄러로 삭제할 시 deletedAt이 존재하는 값들을 삭제 추가
🎯 단독 테스트 결과
- 단위 테스트 TestCode 통해 확인
- PostMan 통해 통합 테스트 확인 완료
- Swagger는 작성이 애매해서 일단 보류해두었습니다!
🚨 연관 이슈
closes #126

S3/Image : BaseEntity 사용한 최적화 리팩토링

---

src/main/java/com/example/picket/domain/seat_holding/service/SeatHoldingService.java

📌 반영 브랜치
feat/booking -> dev
✅ 작업 내용
seatHoldingService의 코드에서 seatHoldingLock 메서드의 코드가 mutable 패턴이라 지양하는 것이 나을 것 같다는 피드백을 받았습니다. 따라서 새로운 리스트를 생성해서 하는 것이 아닌 파라미터로 받는 seatIds 리스트에  stream의 filter와 toList를 사용해서 로직을 수행하도록 개선하였습니다.
또한 기존 for문 사용에서 forEach 사용으로 수정하였습니다.
작업 과정을 블로그에도 올려놓았으니 참고하셔도 좋을 것 같습니다.
https://yubin-code.tistory.com/6
🎯 단독 테스트 결과
Swagger 통해 테스트 확인 완료
🚨 연관 이슈
closes #86

Booking : 좌석 선점 서비스에서 mutable 패턴 제거, forEach 사용으로 변경
